// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AntiSmokingWWDC",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "AntiSmokingWWDC",
            targets: ["AppModule"],
            bundleIdentifier: "com.Antismoking.AntiSmokingWWDC",
            teamIdentifier: "HN837W3RNR",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            resources: [
                .process("AntiSmokingWWDC/3D Models"),
                .copy("AntiSmokingWWDC/3D Models")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("AntiSmokingWWDC/3D Models"),
                .copy("AntiSmokingWWDC/3D Models")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)