// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AntiSmokingWWDC",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "AntiSmokingWWDC",
            targets: ["AppModule"],
            bundleIdentifier: "com.zeptoliquid.AntiSmokingWWDC",
            teamIdentifier: "HN837W3RNR",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "This app requires camera access to show 3D models in augmented reality."),
                .microphone(purposeString: "This app uses the microphone to record your voice."),
                .photoLibrary(purposeString: "This app uses the photo library to save screenshots of your progress.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "AntiSmokingWWDC"
//            ,
//            resources: [
////                .process("Resources")
//            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
